import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { Toaster } from "@/components/ui/toaster"

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'EduLocal App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-secondary p-4">
          <nav>
            <ul className="flex space-x-4">
              <li>
                 <Link href="/welcome" className="hover:text-primary">Bienvenida</Link>
               </li>
              <li>
                <Link href="/user-creation" className="hover:text-primary">Creación de Usuario</Link>
              </li>
               <li>
                <Link href="/user-list" className="hover:text-primary">Lista de Usuarios</Link>
              </li>
              <li>
                <Link href="/course-creation" className="hover:text-primary">Creación de Curso</Link>
              </li>
              <li>
                <Link href="/course-listing" className="hover:text-primary">Listado de Cursos</Link>
              </li>
              <li>
                <Link href="/course-enrollment" className="hover:text-primary">Inscripción a Cursos</Link>
              </li>
              <li>
                <Link href="/courses-by-student" className="hover:text-primary">Cursos por Estudiante</Link>
              </li>
              <li>
                <Link href="/role-display" className="hover:text-primary">Visualización de Roles</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="container mx-auto p-4">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}

